---
 - hosts: dev-nginx
   become: true
   tasks:

    - include: ./common/dev-selinux.yaml

    - include: ./common/dev-epel.yaml

    - include: ./common/dev-hosts.yaml

    - include: ./common/dev-ntp.yaml

    - include: ./dev-nginx/dev-nginx-nginx.yaml

    - include: ./dev-nginx/dev-nginx-squid.yaml

   handlers:     
    - name: restart nginx
      service: name=nginx state=restarted enabled=yes

    - name: restart squid
      service: name=squid state=restarted enabled=yes