---
 - hosts: dev-bastion
   become: true
   tasks:
  
    - group:
        name: backend
        state: present

    - name: add several users
      user:
        name: "{{ item.name }}"
        shell: /bin/bash
        state: present
        groups: "{{ item.groups }}"
      with_items:
        - { name: 'john',   groups: 'backend,wheel' }
        - { name: 'daniel', groups: 'backend,wheel' }
        - { name: 'jason',  groups: 'backend,wheel' }
        - { name: 'eric',   groups: 'backend,wheel' }

    - include: ./dev-bastion/dev-bastion-nat.yaml

    - include: ../common/src/dev-ntp.yaml

    - include: ../common/src/dev-selinux.yaml

    - include: ../common/src/dev-epel.yaml

    - include: ../common/src/dev-hosts.yaml