---
 - hosts: dev-nginx
   become: true
   tasks:

    - include: ./common/dev-selinux.yaml

    - include: ./common/dev-epel.yaml

    - include: ./common/dev-hosts.yaml

    - include: ./common/dev-ntp.yaml

    - name: install nginx
      yum:
        name: nginx 
        state: present

    - name: install squid
      yum:
        name: squid
        state: present

    - name: make sure nginx is running
      service: name=nginx state=started enabled=yes

    - name: Copy squid config file to client
      copy: src=../dev-nginx/src/squid.conf dest=/etc/squid/squid.conf
            owner=root group=root mode=0644
      notify: restart squid
 
    - name: make sure squid is running
      service: name=squid state=started enabled=yes
 
   handlers:     
    - name: restart nginx
      service: name=nginx state=restarted enabled=yes
   
    - name: restart squid
      service: name=squid state=restarted enabled=yes
