---
 - hosts: uat-services
   become: true
   tasks:

    - name: Copy hosts file to client
      copy: src=../hosts dest=/etc/hosts
            owner=root group=root mode=0644

    - name: Copy selinux file to client
      copy: src=../uat-database/src/config dest=/etc/selinux/config
            owner=root group=root mode=0644

    - name: Copy wgetrc file to client
      copy: src=../uat-database/src/wgetrc dest=/etc/wgetrc
            owner=root group=root mode=0644

    - name: Copy profile file to client
      copy: src=../uat-database/src/profile dest=/etc/profile
            owner=root group=root mode=0644

    - name: Copy yum config file to client
      copy: src=../uat-database/src/yum.conf dest=/etc/yum.conf
            owner=root group=root mode=0644
    
    - name: disable selinux
      command: /sbin/setenforce 0
      when: ansible_selinux.status != 'disabled' 

    - name: install epel-release
      yum:
        name: epel-release 
        state: present

    - name: install docker
      yum:
        name: docker-io
        state: present

    - name: mkdir docker config directory
      file: 
        path: /etc/systemd/system/docker.service.d/
        state: directory
        mode: 755

    - name: Copy docker config file to client
      copy: src=../uat-database/src/http-proxy.conf dest=/etc/systemd/system/docker.service.d/http-proxy.conf
            owner=root group=root mode=0644
      notify: restart docker
 
    - name: make sure docker is running
      service: name=docker state=started

    - name: pull nginx image
      command: /usr/bin/docker pull nginx
 
   handlers:     

    - name: restart docker
      service: name=docker state=restarted 
