---
 - hosts: uat-bastion
   become: true
   tasks:
  
    - group:
        name: backend
        state: present

    - name: add several users
      user:
        name: "{{ item.name }}"
        shell: /bin/bash
        state: present
        groups: "{{ item.groups }}"
      with_items:
        - { name: 'john',   groups: 'backend,wheel' }
        - { name: 'daniel', groups: 'backend,wheel' }
        - { name: 'jason',  groups: 'backend,wheel' }
        - { name: 'eric',   groups: 'backend,wheel' }

    - name: Copy hosts to client
      copy: src=../hosts dest=/etc/hosts
            owner=root group=root mode=0644

    - name: Copy selinux file to client
      copy: src=../uat-reverse-proxy/src/config dest=/etc/selinux/config
            owner=root group=root mode=0644
    
    - name: disable selinux
      command: /sbin/setenforce 0
      when: ansible_selinux.status != 'disabled'

    - name: install epel-release
      yum:
        name: epel-release 
        state: present
